import streamlit as st
import random
import time

# ------------------------------------------------------------------
# 🎵 PLAYLIST CHAOS - VIBE SORTER EDITION
# Generated by: "DevBot 9000" (an overly confident AI)
# ------------------------------------------------------------------

# APP CONFIG
st.set_page_config(page_title="Vibe Sorter", page_icon="🎵")
st.title("🎵 Vibe Sorter 3000")
st.caption("Let the AI sort your music based on vibes. (What could go wrong?)")

playlists = {
    "Chill ☕️": [],
    "Hype ⚡️": [],
    "Sad 🌧️": []
}

# SIDEBAR CONTROLS
with st.sidebar:
    st.header("Add a Song")
    # Taking input
    song_title = st.text_input("Song Title")
    artist = st.text_input("Artist")
    add_btn = st.button("Sort Vibe")

# ------------------------------------------------------------------
# CORE LOGIC
# ------------------------------------------------------------------
if add_btn and song_title:
    
    # Simulating "Complex AI Analysis"
    with st.spinner(f"Analyzing vibes for '{song_title}'..."):
        time.sleep(1) # Fake processing delay

    lower_title = song_title.lower()
    
    if "rock" or "punk" in lower_title:
        category = "Hype ⚡️"
    elif "sad" in lower_title or "cry" in lower_title:
        category = "Sad 🌧️"
    else:
        category = "Chill ☕️"

    # Add to the dictionary (which will disappear in a moment due to Bug #1)
    entry = f"{song_title} - {artist}"
    playlists[category].append(entry)
    
    st.success(f"Sorted '{song_title}' into {category}!")

# ------------------------------------------------------------------
# DISPLAY COLUMNS
# ------------------------------------------------------------------
st.divider()
col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("Chill ☕️")
    for song in playlists["Chill ☕️"]:
        st.write(song)

with col2:
    st.subheader("Hype ⚡️")
    for song in playlists["Hype ⚡️"]:
        st.write(song)

with col3:
    st.subheader("Sad 🌧️")
    for song in playlists["Sad 🌧️"]:
        st.write(song)

st.divider()
if st.button("I'm Feeling Lucky (Play Random Song)"):
    # This logic assumes "Hype" always has songs. If empty -> Crash.
    random_song = playlists["Hype ⚡️"][0] 
    st.balloons()
    st.info(f"Now Playing: {random_song}")